# General Kafka and Streams
bootstrap.servers={{CCloud-Bootstrap}}
sasl.mechanism=PLAIN
security.protocol=SASL_SSL
sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required \
   username="{{CCloud-API-Key}}" \
   password="{{CCloud-API-Secret}}";
client.dns.lookup=use_all_dns_ips

acks=all
replication.factor=3
num.standby.replicas=1
#num.stream.threads=3

# Exactly-once processing (transactional producer + fenced zombie instances)
processing.guarantee=exactly_once_v2

# Pipeline
streamsApp.inputTopic=input-topic
streamsApp.outputTopic=output-topic
